config/routes.rb
Collude::Application.routes.draw do
  ActiveAdmin.routes(self)
  resources :comments
  resources :posts
  devise_for :users

  get '/tags/:tag', to: 'posts#tagged'

  root 'posts#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  acts_as_taggable rescue nil
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin_user!
   redirect_to new_user_session_path unless current_user.try(:is_admin?) 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html do
          # @users = User.all

          # # Twilio constants – should be moved to config
          # account_sid = 'ACd619abfb51473fa45265088dbf7cbf7d'
          # account_token = 'a5225b03b9cfee05ffcf539bf58c6492'

          # @twilio_client = Twilio::REST::Client.new account_sid, account_token

          # @users.each do |user|
          #   @twilio_client.account.sms.messages.create(
          #     :from => '+16463621414',
          #     :to => user.phone_number,
          #     :body => "#{current_user.name} just commented on a collude post."
          #   )
          #   logger.info "Text message sent to #{user.name} at #{user.phone_number}."
          # end
          redirect_to root_path, notice: 'Comment was successfully created.'
        end 
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('posts.created_at DESC').all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @autofill = (params[:url]) ? true : false
    @tags = Post.tag_counts.map(&:name)
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @tags = Post.tag_counts.map(&:name)
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
    if @post.save
      format.html do

        @users = User.all

        # Twilio constants – should be moved to config
        account_sid = 'ACd619abfb51473fa45265088dbf7cbf7d'
        account_token = 'a5225b03b9cfee05ffcf539bf58c6492'

        @twilio_client = Twilio::REST::Client.new account_sid, account_token

        @users.each do |user|
          @twilio_client.account.sms.messages.create(
            :from => '+16463621414',
            :to => user.phone_number,
            :body => "#{current_user.name} just created a new post on collude."
          )
          logger.info "Text message sent to #{user.name} at #{user.phone_number}."
        end
        redirect_to @post, notice: 'Post was successfully created.'
      end
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def tagged
    @posts = Post.tagged_with(params[:tag])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:url, :title, :description, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 48 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, class: "gravatar", width: size, height: size, alt: user.name)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Post</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= comment.post %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collude</title>
  <meta name="viewport" content="width=device-width; initial-scale=1.0;">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "The Group", root_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Discussion", root_path %></li>
          <!-- <li><a href="#">Tags</a></li> -->
          <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          <% else %>
            <%= link_to('Login', new_user_session_path)  %>  
          <% end %>
          </li>
        </ul>
        <!-- <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->
      </div><!-- /.navbar-collapse -->
    </nav>    
    
    <hr />

    <% if notice %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </div>

  <nav class="navbar navbar-default navbar-bottom" role="footer" id="footer">
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <p class="navbar-text">Designed and developed by Frank Tisellano in 2013.</p>
     <p class="navbar-text pull-right"><a href="javascript:q=location.href,d=document.getSelection?document.getSelection():'',p=document.title,void%20open('http://www.collude.io/posts/new?url='+encodeURIComponent(q)+'&description='+encodeURIComponent(d)+'&title='+encodeURIComponent(p),'collude','toolbar=no,scrollbars=yes,width=640,height=480');">Drag to Bookmarks</a></p>
    </div>
</nav>
</body>
</html>

app/views/posts/_form.html.erb
<script>
  $(function() {
    var availableTags = <%= @tags.to_json.html_safe %>;
    function split( val ) {
      return val.split( /,\s*/ );
    }
    function extractLast( term ) {
      return split( term ).pop();
    }

    $( "#post_tag_list" )
      // don't navigate away from the field on tab when selecting an item
      .bind( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).data( "ui-autocomplete" ).menu.active ) {
          event.preventDefault();
        }
      })
      .autocomplete({
        minLength: 0,
        source: function( request, response ) {
          // delegate back to autocomplete, but extract the last term
          response( $.ui.autocomplete.filter(
            availableTags, extractLast( request.term ) ) );
        },
        focus: function() {
          // prevent value inserted on focus
          return false;
        },
        select: function( event, ui ) {
          var terms = split( this.value );
          // remove the current input
          terms.pop();
          // add the selected item
          terms.push( ui.item.value );
          // add placeholder to get the comma-and-space at the end
          terms.push( "" );
          this.value = terms.join( ", " );
          return false;
        },
        appendTo: '#tag_group'
      });

      $('.tag-cloud-item').on('click', function() {
        console.log('tag-clound-item')
        var terms = split( $('#post_tag_list').val() );
          // remove the current input
          terms.pop();
          // add the selected item
          terms.push( $(this).attr('data-name') );
          // add placeholder to get the comma-and-space at the end
          terms.push( "" );
          $('#post_tag_list').val(terms.join( ", " ));
          return false;
      })
  });
  </script>
<%= form_for(@post, :html => { role: "form" }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% unless @autofill %>
    <div class="form-group">
      <%= f.label :url, "URL" %><br>
      <%= f.text_field :url, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :url, "URL" %><br>
      <%= f.text_field :url, :class => "form-control", :value => params[:url] %>
    </div>
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => "form-control", :value => params[:title] %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => "form-control", :value => params[:description] %>
    </div>
  <% end %>
    <div class="form-group" id="tag_group">
      <%= f.label :tag_list %>
      <%= f.text_field :tag_list, :class => "form-control" %>
    </div>
    <div class="form-group">
      <% @tags.each do |tag| %>
        <span><a class="tag-cloud-item" href="#" data-name="<%= tag %>"><%= tag %></a><% unless (tag == @tags.last) %>, <% end %></span>
      <% end %>
    </div>
    <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= link_to 'New Post', new_post_path, class: 'new-post btn btn-default btn-sm' %>

<% @posts.each do |post| %>

<div class="post panel panel-default" id="<%= "post-#{post.id}" %>">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to "&rarr; #{post.title}".html_safe, post.url, :target => "_blank" %>
      <% if current_user != post.user %>
      <small><%= link_to 'Edit', edit_post_path(post) %></small>
      <% end %>
    </h3>
    <span class="pull-right post-avatar"><%= gravatar_for(post.user, size: 24) %></span>
  </div>
  <div class="panel-body">
    <p class="lead"><%= simple_format(auto_link(post.description)) %></p>
    <ul class="tags-list pull-left">
      <lh>Tags:</lh>
      <% post.tags.each do |tag| %>
        <li><%= link_to tag.name, "/tags/#{tag.name}" %></li>
      <% end %>
    </ul>
    <p class="text-muted text-right"><%= post.created_at.in_time_zone.strftime("%b %d at %-I:%M %p") %></p>
    <% if post.user == current_user %>
      <p class="text-muted text-right"><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Edit', edit_post_path(post) %></p>
    <% end %>
  </div>
  <ul class="list-group">
  <% post.comments.each do |comment| %>
    <li class="list-group-item clearfix" id="<%= "comment-#{comment.id}" %>">
      <div class="comment-gravatar pull-left"><%= gravatar_for(comment.user, size: 36) %></div>
      <div class="comment-timestamp pull-right"><%= comment.created_at.in_time_zone.strftime("%b %d at %-I:%M %p") %><br />
        <% if comment.user == current_user %>
          <p class="text-muted text-right"><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
      </div>
      <div class="comment-text"><%= simple_format(auto_link(comment.text)) %></div>

    </li>
  <% end %>
    <li class="list-group-item clearfix">
      <%= form_for(Comment.new, :html => { role: "form" }) do |f| %>
        <%= f.text_area :text, :placeholder => "Comment here...", :class => "form-control new-comment-textarea" %>
        <%= f.hidden_field :post_id, :value => post.id %>
        <%= f.submit "Submit", :class => "btn btn-primary btn-sm pull-right new-comment-btn" %>
      <% end %>
    </li>
  </ul>
</div>

<% end %>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>

<p>
  <strong>Tags:</strong>
  <% @post.tag_list.each do |tag| %>
    <%= tag %>
  <% end %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/tagged.html.erb
<h3>Posts tagged with</h3>

<% @posts.each do |post| %>

<div class="post panel panel-default" id="<%= "post-#{post.id}" %>">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to "&rarr; #{post.title}".html_safe, post.url, :target => "_blank" %>
      <% if current_user != post.user %>
      <small><%= link_to 'Edit', edit_post_path(post) %></small>
      <% end %>
    </h3>
    <span class="pull-right post-avatar"><%= gravatar_for(post.user, size: 24) %></span>
  </div>
  <div class="panel-body">
    <p class="lead"><%= post.description %></p>
    <p class="text-muted pull-left">
      Tags:
      <ul class="tags-list">
        <% post.tags.each do |tag| %>
        <li><%= link_to tag.name, "/tags/#{tag.name}" %></li>
        <% end %>
      </ul>
    </p>
    <p class="text-muted text-right"><%= post.created_at.in_time_zone.strftime("%b %d at %-I:%M %p") %></p>
  </div>
  <ul class="list-group">
  <% post.comments.each do |comment| %>
    <li class="list-group-item clearfix" id="<%= "comment-#{comment.id}" %>">
      <div class="comment-gravatar pull-left"><%= gravatar_for(comment.user, size: 36) %></div>
      <div class="comment-timestamp pull-right"><%= comment.created_at.in_time_zone.strftime("%b %d at %-I:%M %p") %></div>
      <div class="comment-text"><%= comment.text %></div>

    </li>
  <% end %>
    <li class="list-group-item clearfix">
      <%= form_for(Comment.new, :html => { role: "form" }) do |f| %>
        <%= f.text_area :text, :placeholder => "Comment here...", :class => "form-control new-comment-textarea" %>
        <%= f.hidden_field :post_id, :value => post.id %>
        <%= f.submit "Submit", :class => "btn btn-primary btn-sm pull-right new-comment-btn" %>
      <% end %>
    </li>
  </ul>
</div>

<% end %>